[package]
name = "rust_forecast"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_forecast"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }

[build-dependencies]
